In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime #for working with times objects
from datetime import timedelta #for working with times objects
import math
import random
import glob

In [2]:
files = ['indego-trips-2021-q1.csv', 'indego-trips-2021-q2.csv', 'indego-trips-2021-q3.csv', 'indego-trips-2021-q4.csv',
        'indego-trips-2022-q1.csv', 'indego-trips-2022-q2.csv', 'indego-trips-2022-q3.csv', 'indego-trips-2022-q4.csv']
df = pd.DataFrame()
for file in files:
    data = pd.read_csv(file)
    df = pd.concat([df, data], axis=0)
df.to_csv('merged_files.csv', index=False)

C:\Users\User\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [3]:
Phil = pd.read_csv("merged_files.csv")

Phil.count()

trip_id                1864918
duration               1864918
start_time             1864918
end_time               1864918
start_station          1864918
start_lat              1864849
start_lon              1864849
end_station            1864918
end_lat                1835665
end_lon                1835665
bike_id                1864918
plan_duration          1864918
trip_route_category    1864918
passholder_type        1864874
bike_type              1864918
dtype: int64

In [4]:
Phil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1864918 entries, 0 to 1864917
Data columns (total 15 columns):
 #   Column               Dtype  
---  ------               -----  
 0   trip_id              int64  
 1   duration             int64  
 2   start_time           object 
 3   end_time             object 
 4   start_station        int64  
 5   start_lat            float64
 6   start_lon            float64
 7   end_station          int64  
 8   end_lat              float64
 9   end_lon              float64
 10  bike_id              object 
 11  plan_duration        int64  
 12  trip_route_category  object 
 13  passholder_type      object 
 14  bike_type            object 
dtypes: float64(4), int64(5), object(6)
memory usage: 213.4+ MB


In [5]:
###check unique values
Phil.nunique()

trip_id                1757653
duration                  1283
start_time              653114
end_time                652354
start_station              199
start_lat                  201
start_lon                  199
end_station                199
end_lat                    203
end_lon                    201
bike_id                   4301
plan_duration                6
trip_route_category          2
passholder_type              4
bike_type                    2
dtype: int64

In [6]:
Phil.head()

trip_id  duration     start_time       end_time  start_station  \
0  365184634        15  1/1/2021 0:05  1/1/2021 0:20           3125   
1  365184633        14  1/1/2021 0:06  1/1/2021 0:20           3022   
2  365184632        33  1/1/2021 0:07  1/1/2021 0:40           3066   
3  365184631         9  1/1/2021 0:13  1/1/2021 0:22           3045   
4  365184630        13  1/1/2021 0:37  1/1/2021 0:50           3052   

   start_lat  start_lon  end_station    end_lat    end_lon bike_id  \
0  39.943909 -75.167351         3157  39.925449 -75.159538   14542   
1  39.954720 -75.183228         3010  39.947109 -75.166183    5294   
2  39.945610 -75.173477         3201  39.955231 -75.166199   14586   
3  39.947922 -75.162369         3034  39.933151 -75.162483   14683   
4  39.947319 -75.156952         3040  39.962891 -75.166061    3330   

   plan_duration trip_route_category passholder_type bike_type  
0             30             One Way        Indego30  standard  
1             30             One Way        Indego30  standard  
2             30             One Way        Indego30  standard  
3             30             One Way        Indego30  standard  
4             30             One Way        Indego30  standard

In [7]:
# check if values are missing
Phil[Phil["start_time"].isnull()==True]
Phil[Phil["end_time"].isnull()==True]
Phil[Phil["start_station"].isnull()==True]
Phil[Phil["end_station"].isnull()==True]
Phil[Phil["start_lat"].isnull()==True]
Phil[Phil["start_lon"].isnull()==True]
Phil[Phil["end_lat"].isnull()==True]
Phil[Phil["end_lon"].isnull()==True]
Phil[Phil["bike_id"].isnull()==True]
Phil[Phil["plan_duration"].isnull()==True]
Phil[Phil["passholder_type"].isnull()==True]

trip_id  duration       start_time         end_time  start_station  \
36035    367443528        11  2/10/2021 12:43  2/10/2021 12:54           3000   
1360957  494975799        22   7/6/2022 12:59   7/6/2022 13:21           3078   
1365735  495355678        18   7/7/2022 19:37   7/7/2022 19:55           3078   
1371276  495739177        27   7/9/2022 16:16   7/9/2022 16:43           3078   
1371278  495738537        10   7/9/2022 16:16   7/9/2022 16:26           3078   
1371336  495739133        13   7/9/2022 16:30   7/9/2022 16:43           3182   
1381437  496783525         4  7/12/2022 17:05  7/12/2022 17:09           3161   
1385479  497172527         1  7/13/2022 18:50  7/13/2022 18:51           3061   
1398420  498661471        21  7/17/2022 16:01  7/17/2022 16:22           3078   
1402111  499047487        25  7/18/2022 19:11  7/18/2022 19:36           3078   
1405397  499495506        22  7/19/2022 19:39  7/19/2022 20:01           3156   
1407396  499686577        32  7/20/2022 14:35  7/20/2022 15:07           3078   
1409611  499932928         9   7/21/2022 6:50   7/21/2022 6:59           3078   
1412946  500310528         6   7/22/2022 6:55   7/22/2022 7:01           3078   
1415564  500585126         4  7/22/2022 21:53  7/22/2022 21:57           3161   
1418203  500936556         1  7/23/2022 21:27  7/23/2022 21:28           3078   
1418204  500936555         5  7/23/2022 21:28  7/23/2022 21:33           3078   
1418213  500936547        16  7/23/2022 21:34  7/23/2022 21:50           3201   
1419788  501113724         1  7/24/2022 15:53  7/24/2022 15:54           3101   
1419789  501123947        21  7/24/2022 15:53  7/24/2022 16:14           3101   
1423957  501647928         7   7/26/2022 6:51   7/26/2022 6:58           3078   
1437655  503115429         7   7/30/2022 9:25   7/30/2022 9:32           3078   
1448933  504237533         5   8/2/2022 18:53   8/2/2022 18:58           3161   
1478931  507425826         2   8/12/2022 7:57   8/12/2022 7:59           3061   
1488046  508328649        20  8/14/2022 19:03  8/14/2022 19:23           3078   
1488991  508530028         2   8/15/2022 7:55   8/15/2022 7:57           3061   
1497486  509336842         8  8/17/2022 12:46  8/17/2022 12:54           3061   
1497888  509378135         7  8/17/2022 14:59  8/17/2022 15:06           3029   
1500355  509658824         2   8/18/2022 7:57   8/18/2022 7:59           3061   
1517044  511533225         2   8/23/2022 8:37   8/23/2022 8:39           3061   
1522285  511975124         5  8/24/2022 16:34  8/24/2022 16:39           3156   
1522355  511976030         5  8/24/2022 16:51  8/24/2022 16:56           3116   
1528017  512631727         3   8/26/2022 7:57   8/26/2022 8:00           3061   
1541480  514367024         4   8/30/2022 8:39   8/30/2022 8:43           3061   
1551761  516102586         6   9/1/2022 22:04   9/1/2022 22:10           3161   
1578441  521380899        10   9/9/2022 19:26   9/9/2022 19:36           3025   
1578453  521380887         7   9/9/2022 19:29   9/9/2022 19:36           3025   
1581528  521984430         9  9/10/2022 17:06  9/10/2022 17:15           3156   
1584089  522798498         1  9/11/2022 20:33  9/11/2022 20:34           3207   
1584090  522798497         9  9/11/2022 20:34  9/11/2022 20:43           3029   
1584092  522798495         8  9/11/2022 20:35  9/11/2022 20:43           3029   
1589481  523775457        16  9/13/2022 14:11  9/13/2022 14:27           3029   
1591835  524080965         3   9/14/2022 0:45   9/14/2022 0:48           3161   
1596492  524952124         2   9/15/2022 7:57   9/15/2022 7:59           3061   

         start_lat  start_lon  end_station    end_lat    end_lon bike_id  \
36035          NaN        NaN         3000        NaN        NaN   19530   
1360957  39.953548 -75.171921         3078  39.953548 -75.171921    2604   
1365735  39.953548 -75.171921         3078  39.953548 -75.171921    5306   
1371276  39.953548 -75.171921         3050  39.953388 -75.154

In [8]:
Phil.dropna(how ='any', inplace=True)

In [9]:
# check if values are missing
Phil[Phil["start_time"].isnull()==True]
Phil[Phil["end_time"].isnull()==True]
Phil[Phil["start_station"].isnull()==True]
Phil[Phil["end_station"].isnull()==True]
Phil[Phil["start_lat"].isnull()==True]
Phil[Phil["start_lon"].isnull()==True]
Phil[Phil["end_lat"].isnull()==True]
Phil[Phil["end_lon"].isnull()==True]
Phil[Phil["bike_id"].isnull()==True]
Phil[Phil["plan_duration"].isnull()==True]
Phil[Phil["passholder_type"].isnull()==True]

Empty DataFrame
Columns: [trip_id, duration, start_time, end_time, start_station, start_lat, start_lon, end_station, end_lat, end_lon, bike_id, plan_duration, trip_route_category, passholder_type, bike_type]
Index: []

<H3>We would like to add a categorical value for the day of the week to be able to access it easier later on.</H3>

In [10]:
Phil["start_time"] = pd.to_datetime(Phil["start_time"])
Phil["end_time"] = pd.to_datetime(Phil["end_time"])

In [11]:
# Let's map time of day and day of week to our DF

def get_date (ts):
    return ts.date()

def get_weekday (ts):
    return ts.weekday()

def get_hour (ts):
    return ts.hour

In [12]:
#Phil.reset_index(inplace=True)
Phil["Date_s"] = Phil["start_time"].apply(lambda ts: get_date (ts))
Phil["Weekday_s"]=Phil["start_time"].apply(lambda x: get_weekday (x))
Phil["Hour_s"]=Phil["start_time"].apply(lambda x: get_hour (x))
Phil["Date_e"] = Phil["end_time"].apply(lambda ts: get_date (ts))
Phil["Weekday_e"]=Phil["end_time"].apply(lambda x: get_weekday (x))
Phil["Hour_e"]=Phil["end_time"].apply(lambda x: get_hour (x))

In [13]:
Phil

trip_id  duration          start_time            end_time  \
0        365184634        15 2021-01-01 00:05:00 2021-01-01 00:20:00   
1        365184633        14 2021-01-01 00:06:00 2021-01-01 00:20:00   
2        365184632        33 2021-01-01 00:07:00 2021-01-01 00:40:00   
3        365184631         9 2021-01-01 00:13:00 2021-01-01 00:22:00   
4        365184630        13 2021-01-01 00:37:00 2021-01-01 00:50:00   
...            ...       ...                 ...                 ...   
1864913  579499101        23 2022-12-31 23:44:00 2023-01-01 00:07:00   
1864914  579499099        17 2022-12-31 23:45:00 2023-01-01 00:02:00   
1864915  579499097         8 2022-12-31 23:51:00 2022-12-31 23:59:00   
1864916  579499095        23 2022-12-31 23:54:00 2023-01-01 00:16:00   
1864917  579499093        62 2022-12-31 23:54:00 2023-01-01 00:56:00   

         start_station  start_lat  start_lon  end_station    end_lat  \
0                 3125  39.943909 -75.167351         3157  39.925449   
1                 3022  39.954720 -75.183228         3010  39.947109   
2                 3066  39.945610 -75.173477         3201  39.955231   
3                 3045  39.947922 -75.162369         3034  39.933151   
4                 3052  39.947319 -75.156952         3040  39.962891   
...                ...        ...        ...          ...        ...   
1864913           3244  39.938648 -75.166740         3287  39.943668   
1864914           3295  39.950279 -75.160271         3054  39.962502   
1864915           3255  39.950951 -75.164383         3046  39.950119   
1864916           3255  39.950951 -75.164383         3113  39.974720   
1864917           3161  39.954861 -75.180908         3010  39.947109   

           end_lon  ... plan_duration  trip_route_category passholder_type  \
0       -75.159538  ...            30              One Way        Indego30   
1       -75.166183  ...            30              One Way        Indego30   
2       -75.166199  ...            30              One Way        Indego30   
3       -75.162483  ...            30              One Way        Indego30   
4       -75.166061  ...            30              One Way        Indego30   
...            ...  ...           ...                  ...             ...   
1864913 -75.216057  ...            30              One Way        Indego30   
1864914 -75.174202  ...            30              One Way        Indego30   
1864915 -75.144722  ...            30              One Way        Indego30   
1864916 -75.197807  ...            30              One Way        Indego30   
1864917 -75.166183  ...            30              One Way        Indego30   

        bike_type      Date_s Weekday_s  Hour_s      Date_e Weekday_e  Hour_e  
0        standard  2021-01-01         4       0  2021-01-01         4       0  
1        standard  2021-01-01         4       0  2021-01-01         4       0  
2        standard  2021-01-01         4       0  2021-01-01         4       0  
3        standard  2021-01-01         4       0  2021-01-01         4       0  
4        standard  2021-01-01         4       0  2021-01-01         4       0  
...           ...         ...       ...     ...         ...       ...     ...  
1864913  standard  2022-12-31         5      23  2023-01-01         6       0  
1864914  electric  2022-12-31         5      23  2023-01-01         6       0  
1864915  electric  2022-12-31         5      23  2022-12-31         5      23  
1864916  electric  2022-12-31         5      23  2023-01-01         6       0  
1864917  standard  2022-12-31         5      23  2023-01-01         6       0  

[1835611 rows x 21 columns]

<H4>Now we would like to check the range of the duration-values to clean our dataset of erroneous entries</H4>

In [14]:
minValueDurationMS = Phil.min()
minValueDurationMS

trip_id                          365184627
duration                                 1
start_time             2021-01-01 00:05:00
end_time               2021-01-01 00:20:00
start_station                         3004
start_lat                        39.889938
start_lon                       -75.229462
end_station                           3000
end_lat                          39.889938
end_lon                         -75.229462
plan_duration                            1
trip_route_category                One Way
passholder_type                   Day Pass
bike_type                         electric
Date_s                          2021-01-01
Weekday_s                                0
Hour_s                                   0
Date_e                          2021-01-01
Weekday_e                                0
Hour_e                                   0
dtype: object

In [15]:
maxValueDurationMS = Phil.max()
maxValueDurationMS

trip_id                          579859025
duration                              1440
start_time             2022-12-31 23:54:00
end_time               2023-01-02 10:42:00
start_station                         3300
start_lat                         40.01112
start_lon                       -75.121567
end_station                           3300
end_lat                           40.01112
end_lon                         -75.121567
plan_duration                          365
trip_route_category             Round Trip
passholder_type                    Walk-up
bike_type                         standard
Date_s                          2022-12-31
Weekday_s                                6
Hour_s                                  23
Date_e                          2023-01-02
Weekday_e                                6
Hour_e                                  23
dtype: object

<H4>We want to get rid of all data which shows a negative duration and the data with a longer duration than 24h because by Ride Indego Philadelphia policy a bike is marked as stolen and a fine is issued after the ride-time exceeds 24h. </H4>

In [16]:
durationMin = 1 #minutes
durationMax = 1440 #minutes equals 24h

Phil.drop(Phil[Phil["duration"]<durationMin].index, inplace = True)
Phil.drop(Phil[Phil["duration"]>durationMax].index, inplace = True)

Phil

trip_id  duration          start_time            end_time  \
0        365184634        15 2021-01-01 00:05:00 2021-01-01 00:20:00   
1        365184633        14 2021-01-01 00:06:00 2021-01-01 00:20:00   
2        365184632        33 2021-01-01 00:07:00 2021-01-01 00:40:00   
3        365184631         9 2021-01-01 00:13:00 2021-01-01 00:22:00   
4        365184630        13 2021-01-01 00:37:00 2021-01-01 00:50:00   
...            ...       ...                 ...                 ...   
1864913  579499101        23 2022-12-31 23:44:00 2023-01-01 00:07:00   
1864914  579499099        17 2022-12-31 23:45:00 2023-01-01 00:02:00   
1864915  579499097         8 2022-12-31 23:51:00 2022-12-31 23:59:00   
1864916  579499095        23 2022-12-31 23:54:00 2023-01-01 00:16:00   
1864917  579499093        62 2022-12-31 23:54:00 2023-01-01 00:56:00   

         start_station  start_lat  start_lon  end_station    end_lat  \
0                 3125  39.943909 -75.167351         3157  39.925449   
1                 3022  39.954720 -75.183228         3010  39.947109   
2                 3066  39.945610 -75.173477         3201  39.955231   
3                 3045  39.947922 -75.162369         3034  39.933151   
4                 3052  39.947319 -75.156952         3040  39.962891   
...                ...        ...        ...          ...        ...   
1864913           3244  39.938648 -75.166740         3287  39.943668   
1864914           3295  39.950279 -75.160271         3054  39.962502   
1864915           3255  39.950951 -75.164383         3046  39.950119   
1864916           3255  39.950951 -75.164383         3113  39.974720   
1864917           3161  39.954861 -75.180908         3010  39.947109   

           end_lon  ... plan_duration  trip_route_category passholder_type  \
0       -75.159538  ...            30              One Way        Indego30   
1       -75.166183  ...            30              One Way        Indego30   
2       -75.166199  ...            30              One Way        Indego30   
3       -75.162483  ...            30              One Way        Indego30   
4       -75.166061  ...            30              One Way        Indego30   
...            ...  ...           ...                  ...             ...   
1864913 -75.216057  ...            30              One Way        Indego30   
1864914 -75.174202  ...            30              One Way        Indego30   
1864915 -75.144722  ...            30              One Way        Indego30   
1864916 -75.197807  ...            30              One Way        Indego30   
1864917 -75.166183  ...            30              One Way        Indego30   

        bike_type      Date_s Weekday_s  Hour_s      Date_e Weekday_e  Hour_e  
0        standard  2021-01-01         4       0  2021-01-01         4       0  
1        standard  2021-01-01         4       0  2021-01-01         4       0  
2        standard  2021-01-01         4       0  2021-01-01         4       0  
3        standard  2021-01-01         4       0  2021-01-01         4       0  
4        standard  2021-01-01         4       0  2021-01-01         4       0  
...           ...         ...       ...     ...         ...       ...     ...  
1864913  standard  2022-12-31         5      23  2023-01-01         6       0  
1864914  electric  2022-12-31         5      23  2023-01-01         6       0  
1864915  electric  2022-12-31         5      23  2022-12-31         5      23  
1864916  electric  2022-12-31         5      23  2023-01-01         6       0  
1864917  standard  2022-12-31         5      23  2023-01-01         6       0  

[1835611 rows x 21 columns]

<H4>Now we would like to delete all rows with a duration of less than 3 minutes where the start and end station are the same (no real ride).</H4>

In [17]:
Phil_limited = Phil[(Phil["start_station"]==Phil["end_station"]) & (Phil["duration"] <= 3)]
Phil_limited.count()

trip_id                54090
duration               54090
start_time             54090
end_time               54090
start_station          54090
start_lat              54090
start_lon              54090
end_station            54090
end_lat                54090
end_lon                54090
bike_id                54090
plan_duration          54090
trip_route_category    54090
passholder_type        54090
bike_type              54090
Date_s                 54090
Weekday_s              54090
Hour_s                 54090
Date_e                 54090
Weekday_e              54090
Hour_e                 54090
dtype: int64

Now we want to delete all of these 54090rows!

In [18]:
Phil.drop(Phil[((Phil["start_station"])==(Phil["end_station"])) & (Phil["duration"] <= 3)].index, inplace=True)
Phil

trip_id  duration          start_time            end_time  \
0        365184634        15 2021-01-01 00:05:00 2021-01-01 00:20:00   
1        365184633        14 2021-01-01 00:06:00 2021-01-01 00:20:00   
2        365184632        33 2021-01-01 00:07:00 2021-01-01 00:40:00   
3        365184631         9 2021-01-01 00:13:00 2021-01-01 00:22:00   
4        365184630        13 2021-01-01 00:37:00 2021-01-01 00:50:00   
...            ...       ...                 ...                 ...   
1864913  579499101        23 2022-12-31 23:44:00 2023-01-01 00:07:00   
1864914  579499099        17 2022-12-31 23:45:00 2023-01-01 00:02:00   
1864915  579499097         8 2022-12-31 23:51:00 2022-12-31 23:59:00   
1864916  579499095        23 2022-12-31 23:54:00 2023-01-01 00:16:00   
1864917  579499093        62 2022-12-31 23:54:00 2023-01-01 00:56:00   

         start_station  start_lat  start_lon  end_station    end_lat  \
0                 3125  39.943909 -75.167351         3157  39.925449   
1                 3022  39.954720 -75.183228         3010  39.947109   
2                 3066  39.945610 -75.173477         3201  39.955231   
3                 3045  39.947922 -75.162369         3034  39.933151   
4                 3052  39.947319 -75.156952         3040  39.962891   
...                ...        ...        ...          ...        ...   
1864913           3244  39.938648 -75.166740         3287  39.943668   
1864914           3295  39.950279 -75.160271         3054  39.962502   
1864915           3255  39.950951 -75.164383         3046  39.950119   
1864916           3255  39.950951 -75.164383         3113  39.974720   
1864917           3161  39.954861 -75.180908         3010  39.947109   

           end_lon  ... plan_duration  trip_route_category passholder_type  \
0       -75.159538  ...            30              One Way        Indego30   
1       -75.166183  ...            30              One Way        Indego30   
2       -75.166199  ...            30              One Way        Indego30   
3       -75.162483  ...            30              One Way        Indego30   
4       -75.166061  ...            30              One Way        Indego30   
...            ...  ...           ...                  ...             ...   
1864913 -75.216057  ...            30              One Way        Indego30   
1864914 -75.174202  ...            30              One Way        Indego30   
1864915 -75.144722  ...            30              One Way        Indego30   
1864916 -75.197807  ...            30              One Way        Indego30   
1864917 -75.166183  ...            30              One Way        Indego30   

        bike_type      Date_s Weekday_s  Hour_s      Date_e Weekday_e  Hour_e  
0        standard  2021-01-01         4       0  2021-01-01         4       0  
1        standard  2021-01-01         4       0  2021-01-01         4       0  
2        standard  2021-01-01         4       0  2021-01-01         4       0  
3        standard  2021-01-01         4       0  2021-01-01         4       0  
4        standard  2021-01-01         4       0  2021-01-01         4       0  
...           ...         ...       ...     ...         ...       ...     ...  
1864913  standard  2022-12-31         5      23  2023-01-01         6       0  
1864914  electric  2022-12-31         5      23  2023-01-01         6       0  
1864915  electric  2022-12-31         5      23  2022-12-31         5      23  
1864916  electric  2022-12-31         5      23  2023-01-01         6       0  
1864917  standard  2022-12-31         5      23  2023-01-01         6       0  

[1781521 rows x 21 columns]

In [19]:
###check unique values
Phil.nunique()

trip_id                1679197
duration                  1255
start_time              642441
end_time                640604
start_station              198
start_lat                  201
start_lon                  199
end_station                199
end_lat                    203
end_lon                    201
bike_id                   4284
plan_duration                5
trip_route_category          2
passholder_type              4
bike_type                    2
Date_s                     730
Weekday_s                    7
Hour_s                      24
Date_e                     732
Weekday_e                    7
Hour_e                      24
dtype: int64

<H4>We noticed that the number of stations and their coordinates differs.</H4>

In [20]:
Phil.groupby("start_station").agg({"start_lat": "unique", "start_lon": "unique"})

start_lat  \
start_station                                      
3004                                 [39.953781]   
3005                                  [39.94733]   
3006                                 [39.952202]   
3007                                 [39.945171]   
3008           [39.980782, 39.979439, 39.980808]   
...                                          ...   
3295                                 [39.950279]   
3296                                  [39.95134]   
3298                                  [39.94717]   
3299                                 [39.943321]   
3300                                 [39.955109]   

                                          start_lon  
start_station                                        
3004                                   [-75.163742]  
3005                                   [-75.144028]  
3006                                    [-75.20311]  
3007                                   [-75.159927]  
3008           [-75.150551, -75.151138, -75.150673]  
...                                             ...  
3295                                   [-75.160271]  
3296                                    [-75.16758]  
3298                                   [-75.206909]  
3299                                   [-75.156982]  
3300                                   [-75.162872]  

[198 rows x 2 columns]

In [21]:
Phil.loc[Phil.start_station.isin([3008, 3039, 3047, 3124, 3166, 3212]), "start_lon"].iloc[0]

-75.159698

In [22]:
for station in [3008, 3039, 3047, 3124, 3166, 3212]:
    new_lon = Phil.loc[Phil.start_station == station, "start_lon"].iloc[0]
    new_lat = Phil.loc[Phil.start_station == station, "start_lat"].iloc[0]
    Phil.loc[Phil.start_station == station, "start_lon"] = new_lon
    Phil.loc[Phil.start_station == station, "start_lat"] = new_lat

In [23]:
x = Phil.groupby("start_station").agg({"start_lat": "unique", "start_lon": "unique"})

In [24]:
np.unique(x.start_lon, return_counts = True)

(array([array([-75.229462]), array([-75.226372]), array([-75.224243]),
        array([-75.223991]), array([-75.223007]), array([-75.220482]),
        array([-75.218246]), array([-75.216202]), array([-75.216057]),
        array([-75.215141]), array([-75.213623]), array([-75.213226]),
        array([-75.212784]), array([-75.211853]), array([-75.209869]),
        array([-75.209084]), array([-75.208099]), array([-75.207993]),
        array([-75.206909]), array([-75.20311]), array([-75.202858]),
        array([-75.19973]), array([-75.199623]), array([-75.198837]),
        array([-75.198624]), array([-75.197807]), array([-75.196999]),
        array([-75.196487]), array([-75.196327]), array([-75.195511]),
        array([-75.194794]), array([-75.194191]), array([-75.194092]),
        array([-75.193237]), array([-75.193192]), array([-75.192871]),
        array([-75.192093]), array([-75.192001]), array([-75.191963]),
        array([-75.190788]), array([-75.190071]), array([-75.189957]),
        

In [25]:
###check unique values
Phil.nunique()

trip_id                1679197
duration                  1255
start_time              642441
end_time                640604
start_station              198
start_lat                  194
start_lon                  194
end_station                199
end_lat                    203
end_lon                    201
bike_id                   4284
plan_duration                5
trip_route_category          2
passholder_type              4
bike_type                    2
Date_s                     730
Weekday_s                    7
Hour_s                      24
Date_e                     732
Weekday_e                    7
Hour_e                      24
dtype: int64

As we cleaned the start stations, we now noticed that there are 4 stations, that have the same coordinates as some other stations. This could be because they were possibly renamed at some point.

Next, the same procedure for the end stations.

In [26]:
Phil.groupby("end_station").agg({"end_lat": "unique", "end_lon": "unique"})


end_lat                  end_lon
end_station                                                 
3000         [39.949421, 39.915909]  [-75.16613, -75.183701]
3004                    [39.953781]             [-75.163742]
3005                     [39.94733]             [-75.144028]
3006                    [39.952202]              [-75.20311]
3007                    [39.945171]             [-75.159927]
...                             ...                      ...
3295                    [39.950279]             [-75.160271]
3296                     [39.95134]              [-75.16758]
3298                     [39.94717]             [-75.206909]
3299                    [39.943321]             [-75.156982]
3300                    [39.955109]             [-75.162872]

[199 rows x 2 columns]

In [27]:
Phil.loc[Phil.end_station.isin([3000, 3008, 3039, 3047, 3124, 3166, 3212]), "end_lon"].iloc[0]

-75.159698

In [28]:
for station in [3000, 3008, 3039, 3047, 3124, 3166, 3212]:
    new_lon_e = Phil.loc[Phil.end_station == station, "end_lon"].iloc[0]
    new_lat_e = Phil.loc[Phil.end_station == station, "end_lat"].iloc[0]
    Phil.loc[Phil.end_station == station, "end_lon"] = new_lon_e
    Phil.loc[Phil.end_station == station, "end_lat"] = new_lat_e

In [29]:
x = Phil.groupby("end_station").agg({"end_lat": "unique", "end_lon": "unique"})

In [30]:
np.unique(x.end_lon, return_counts = True)

(array([array([-75.229462]), array([-75.226372]), array([-75.224243]),
        array([-75.223991]), array([-75.223007]), array([-75.220482]),
        array([-75.218246]), array([-75.216202]), array([-75.216057]),
        array([-75.215141]), array([-75.213623]), array([-75.213226]),
        array([-75.212784]), array([-75.211853]), array([-75.209869]),
        array([-75.209084]), array([-75.208099]), array([-75.207993]),
        array([-75.206909]), array([-75.20311]), array([-75.202858]),
        array([-75.19973]), array([-75.199623]), array([-75.198837]),
        array([-75.198624]), array([-75.197807]), array([-75.196999]),
        array([-75.196487]), array([-75.196327]), array([-75.195511]),
        array([-75.194794]), array([-75.194191]), array([-75.194092]),
        array([-75.193237]), array([-75.193192]), array([-75.192871]),
        array([-75.192093]), array([-75.192001]), array([-75.191963]),
        array([-75.190788]), array([-75.190071]), array([-75.189957]),
        

In [31]:
###check unique values
Phil.nunique()

trip_id                1679197
duration                  1255
start_time              642441
end_time                640604
start_station              198
start_lat                  194
start_lon                  194
end_station                199
end_lat                    195
end_lon                    195
bike_id                   4284
plan_duration                5
trip_route_category          2
passholder_type              4
bike_type                    2
Date_s                     730
Weekday_s                    7
Hour_s                      24
Date_e                     732
Weekday_e                    7
Hour_e                      24
dtype: int64

Now there is one end station, that is not a start station. We want to find it.

In [32]:
# Find the value that appears in end_station but not in start_station
end_station_unique = set(Phil["end_station"]).difference(set(Phil["start_station"]))

# Print the unique value
print(end_station_unique)

{3000}


We decided to drop this station, as it could be a technical location, where the bikes are checked, or maybe a main facility location. In any case, bikes can't be rented from there and trips can't start from there, so they are not so relevant for us.

In [33]:
Phil.drop(Phil.loc[Phil['end_station']==3000].index, inplace=True)
Phil

trip_id  duration          start_time            end_time  \
0        365184634        15 2021-01-01 00:05:00 2021-01-01 00:20:00   
1        365184633        14 2021-01-01 00:06:00 2021-01-01 00:20:00   
2        365184632        33 2021-01-01 00:07:00 2021-01-01 00:40:00   
3        365184631         9 2021-01-01 00:13:00 2021-01-01 00:22:00   
4        365184630        13 2021-01-01 00:37:00 2021-01-01 00:50:00   
...            ...       ...                 ...                 ...   
1864913  579499101        23 2022-12-31 23:44:00 2023-01-01 00:07:00   
1864914  579499099        17 2022-12-31 23:45:00 2023-01-01 00:02:00   
1864915  579499097         8 2022-12-31 23:51:00 2022-12-31 23:59:00   
1864916  579499095        23 2022-12-31 23:54:00 2023-01-01 00:16:00   
1864917  579499093        62 2022-12-31 23:54:00 2023-01-01 00:56:00   

         start_station  start_lat  start_lon  end_station    end_lat  \
0                 3125  39.943909 -75.167351         3157  39.925449   
1                 3022  39.954720 -75.183228         3010  39.947109   
2                 3066  39.945610 -75.173477         3201  39.955231   
3                 3045  39.947922 -75.162369         3034  39.933151   
4                 3052  39.947319 -75.156952         3040  39.962891   
...                ...        ...        ...          ...        ...   
1864913           3244  39.938648 -75.166740         3287  39.943668   
1864914           3295  39.950279 -75.160271         3054  39.962502   
1864915           3255  39.950951 -75.164383         3046  39.950119   
1864916           3255  39.950951 -75.164383         3113  39.974720   
1864917           3161  39.954861 -75.180908         3010  39.947109   

           end_lon  ... plan_duration  trip_route_category passholder_type  \
0       -75.159538  ...            30              One Way        Indego30   
1       -75.166183  ...            30              One Way        Indego30   
2       -75.166199  ...            30              One Way        Indego30   
3       -75.162483  ...            30              One Way        Indego30   
4       -75.166061  ...            30              One Way        Indego30   
...            ...  ...           ...                  ...             ...   
1864913 -75.216057  ...            30              One Way        Indego30   
1864914 -75.174202  ...            30              One Way        Indego30   
1864915 -75.144722  ...            30              One Way        Indego30   
1864916 -75.197807  ...            30              One Way        Indego30   
1864917 -75.166183  ...            30              One Way        Indego30   

        bike_type      Date_s Weekday_s  Hour_s      Date_e Weekday_e  Hour_e  
0        standard  2021-01-01         4       0  2021-01-01         4       0  
1        standard  2021-01-01         4       0  2021-01-01         4       0  
2        standard  2021-01-01         4       0  2021-01-01         4       0  
3        standard  2021-01-01         4       0  2021-01-01         4       0  
4        standard  2021-01-01         4       0  2021-01-01         4       0  
...           ...         ...       ...     ...         ...       ...     ...  
1864913  standard  2022-12-31         5      23  2023-01-01         6       0  
1864914  electric  2022-12-31         5      23  2023-01-01         6       0  
1864915  electric  2022-12-31         5      23  2022-12-31         5      23  
1864916  electric  2022-12-31         5      23  2023-01-01         6       0  
1864917  standard  2022-12-31         5      23  2023-01-01         6       0  

[1781474 rows x 21 columns]

In [37]:
Phil['start_lat'] = Phil['start_lat'].astype(str)
Phil['start_lon'] = Phil['start_lon'].astype(str)
Phil['end_lat'] = Phil['end_lat'].astype(str)
Phil['end_lon'] = Phil['end_lon'].astype(str)

In [38]:
Phil['start_coordinates'] = Phil[['start_lat', 'start_lon']].agg(','.join, axis=1)
Phil['end_coordinates'] = Phil[['end_lat', 'end_lon']].agg(','.join, axis=1)

In [39]:
Phil.head()

trip_id  duration          start_time            end_time  start_station  \
0  365184634        15 2021-01-01 00:05:00 2021-01-01 00:20:00           3125   
1  365184633        14 2021-01-01 00:06:00 2021-01-01 00:20:00           3022   
2  365184632        33 2021-01-01 00:07:00 2021-01-01 00:40:00           3066   
3  365184631         9 2021-01-01 00:13:00 2021-01-01 00:22:00           3045   
4  365184630        13 2021-01-01 00:37:00 2021-01-01 00:50:00           3052   

   start_lat   start_lon  end_station    end_lat     end_lon  ...  \
0  39.943909  -75.167351         3157  39.925449  -75.159538  ...   
1   39.95472  -75.183228         3010  39.947109  -75.166183  ...   
2   39.94561  -75.173477         3201  39.955231  -75.166199  ...   
3  39.947922  -75.162369         3034  39.933151  -75.162483  ...   
4  39.947319  -75.156952         3040  39.962891  -75.166061  ...   

  passholder_type  bike_type      Date_s Weekday_s Hour_s      Date_e  \
0        Indego30   standard  2021-01-01         4      0  2021-01-01   
1        Indego30   standard  2021-01-01         4      0  2021-01-01   
2        Indego30   standard  2021-01-01         4      0  2021-01-01   
3        Indego30   standard  2021-01-01         4      0  2021-01-01   
4        Indego30   standard  2021-01-01         4      0  2021-01-01   

   Weekday_e  Hour_e     start_coordinates       end_coordinates  
0          4       0  39.943909,-75.167351  39.925449,-75.159538  
1          4       0   39.95472,-75.183228  39.947109,-75.166183  
2          4       0   39.94561,-75.173477  39.955231,-75.166199  
3          4       0  39.947922,-75.162369  39.933151,-75.162483  
4          4       0  39.947319,-75.156952  39.962891,-75.166061  

[5 rows x 23 columns]

In [40]:
Phil = Phil.drop('start_lat' , axis=1)
Phil = Phil.drop('start_lon' , axis=1)
Phil = Phil.drop('end_lat' , axis=1)
Phil = Phil.drop('end_lon' , axis=1)

In [41]:
Phil.head()

trip_id  duration          start_time            end_time  start_station  \
0  365184634        15 2021-01-01 00:05:00 2021-01-01 00:20:00           3125   
1  365184633        14 2021-01-01 00:06:00 2021-01-01 00:20:00           3022   
2  365184632        33 2021-01-01 00:07:00 2021-01-01 00:40:00           3066   
3  365184631         9 2021-01-01 00:13:00 2021-01-01 00:22:00           3045   
4  365184630        13 2021-01-01 00:37:00 2021-01-01 00:50:00           3052   

   end_station bike_id  plan_duration trip_route_category passholder_type  \
0         3157   14542             30             One Way        Indego30   
1         3010    5294             30             One Way        Indego30   
2         3201   14586             30             One Way        Indego30   
3         3034   14683             30             One Way        Indego30   
4         3040    3330             30             One Way        Indego30   

  bike_type      Date_s  Weekday_s  Hour_s      Date_e  Weekday_e  Hour_e  \
0  standard  2021-01-01          4       0  2021-01-01          4       0   
1  standard  2021-01-01          4       0  2021-01-01          4       0   
2  standard  2021-01-01          4       0  2021-01-01          4       0   
3  standard  2021-01-01          4       0  2021-01-01          4       0   
4  standard  2021-01-01          4       0  2021-01-01          4       0   

      start_coordinates       end_coordinates  
0  39.943909,-75.167351  39.925449,-75.159538  
1   39.95472,-75.183228  39.947109,-75.166183  
2   39.94561,-75.173477  39.955231,-75.166199  
3  39.947922,-75.162369  39.933151,-75.162483  
4  39.947319,-75.156952  39.962891,-75.166061

In [42]:
###check unique values
Phil.nunique()

trip_id                1679150
duration                  1255
start_time              642434
end_time                640598
start_station              198
end_station                198
bike_id                   4284
plan_duration                5
trip_route_category          2
passholder_type              4
bike_type                    2
Date_s                     730
Weekday_s                    7
Hour_s                      24
Date_e                     732
Weekday_e                    7
Hour_e                      24
start_coordinates          196
end_coordinates            196
dtype: int64

In [43]:
Phil

trip_id  duration          start_time            end_time  \
0        365184634        15 2021-01-01 00:05:00 2021-01-01 00:20:00   
1        365184633        14 2021-01-01 00:06:00 2021-01-01 00:20:00   
2        365184632        33 2021-01-01 00:07:00 2021-01-01 00:40:00   
3        365184631         9 2021-01-01 00:13:00 2021-01-01 00:22:00   
4        365184630        13 2021-01-01 00:37:00 2021-01-01 00:50:00   
...            ...       ...                 ...                 ...   
1864913  579499101        23 2022-12-31 23:44:00 2023-01-01 00:07:00   
1864914  579499099        17 2022-12-31 23:45:00 2023-01-01 00:02:00   
1864915  579499097         8 2022-12-31 23:51:00 2022-12-31 23:59:00   
1864916  579499095        23 2022-12-31 23:54:00 2023-01-01 00:16:00   
1864917  579499093        62 2022-12-31 23:54:00 2023-01-01 00:56:00   

         start_station  end_station bike_id  plan_duration  \
0                 3125         3157   14542             30   
1                 3022         3010    5294             30   
2                 3066         3201   14586             30   
3                 3045         3034   14683             30   
4                 3052         3040    3330             30   
...                ...          ...     ...            ...   
1864913           3244         3287   14674             30   
1864914           3295         3054   23113             30   
1864915           3255         3046   16897             30   
1864916           3255         3113   22646             30   
1864917           3161         3010   13100             30   

        trip_route_category passholder_type bike_type      Date_s  Weekday_s  \
0                   One Way        Indego30  standard  2021-01-01          4   
1                   One Way        Indego30  standard  2021-01-01          4   
2                   One Way        Indego30  standard  2021-01-01          4   
3                   One Way        Indego30  standard  2021-01-01          4   
4                   One Way        Indego30  standard  2021-01-01          4   
...                     ...             ...       ...         ...        ...   
1864913             One Way        Indego30  standard  2022-12-31          5   
1864914             One Way        Indego30  electric  2022-12-31          5   
1864915             One Way        Indego30  electric  2022-12-31          5   
1864916             One Way        Indego30  electric  2022-12-31          5   
1864917             One Way        Indego30  standard  2022-12-31          5   

         Hour_s      Date_e  Weekday_e  Hour_e     start_coordinates  \
0             0  2021-01-01          4       0  39.943909,-75.167351   
1             0  2021-01-01          4       0   39.95472,-75.183228   
2             0  2021-01-01          4       0   39.94561,-75.173477   
3             0  2021-01-01          4       0  39.947922,-75.162369   
4             0  2021-01-01          4       0  39.947319,-75.156952   
...         ...         ...        ...     ...                   ...   
1864913      23  2023-01-01          6       0   39.938648,-75.16674   
1864914      23  2023-01-01          6       0  39.950279,-75.160271   
1864915      23  2022-12-31          5      23  39.950951,-75.164383   
1864916      23  2023-01-01          6       0  39.950951,-75.164383   
1864917      23  2023-01-01          6       0  39.954861,-75.180908   

              end_coordinates  
0        39.925449,-75.159538  
1        39.947109,-75.166183  
2        39.955231,-75.166199  
3        39.933151,-75.162483  
4        39.962891,-75.166061  
...                       ...  
1864913  39.943668,-75.216057  
1864914  39.962502,-75.174202  
1864915  39.950119,-75.144722  
1864916   39.97472,-75.197807  
1864917  39.947109,-75.166183  

[1781474 rows x 19 columns]